[package]
name = "zkfetch-notary-worker"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.8.7"

[profile.release]
lto = true
# wasm-bindgen >=0.2.125 needs the externref table names during bundling.
strip = "debuginfo"
codegen-units = 1
